server: 
  port: 9001

spring: 
  application: 
    name: mgt-app
  devtools: 
    restart: 
      enabled: true

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:9000/eureka

