FROM openjdk:21
LABEL maintainer ="kamal"
ADD target/springbootJwtPocWithAngular-0.0.1-SNAPSHOT.jar springbootJwtPocWithAngular-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","springbootJwtPocWithAngular-0.0.1-SNAPSHOT.jar"]