server: 
  port: 9000
spring: 
  application: 
    name: jpa-demo-h2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2: 
    console: 
      enabled: true

  jpa: 
    show-sql: true
    
#    properties: 
#      hibernate: 
#        format_sql: true

#logging: 
#  level: 
#    org.springframework: debug
#    com.skh: debug
